# Welcome to Jekyll!
#

# Site settings
title: Joshua Salyer
description: |
  Web Developer
owner: Joshua Salyer # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: joshsalyer23@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/joshsalyer23
  github: https://github.com/jsalyer23
  linkedin-square: https://linkedin.com/in/joshua-salyer-56677b127
  facebook-official: https://facebook.com/joshsalyer23
  google-plus-square: 
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

